#!/usr/bin/env python3
'''
Experiment with simplex noise.
2D noise → 1D noise in time.
'''
import math
import random
import sys
import time

from pyutil.caseleds import Leds, SimplexMode

mode = sys.argv[1]
leds = Leds()

schemes = {
'purple2': ([150, 0,   255], [255, 0,   222]),
'greeny':  ([10,  255, 0  ], [200, 255, 0]),
'autumn':  ([255, 20,  0  ], [255, 200, 0]),
'redgrey': ([255, 0,   0  ], [25,  25,  25]),
'cyan':    ([0,   220, 120], [0,   0,  255]),
'cyangrey':([0,   255, 250], [128, 128,128]),
}

if mode == 'colorful': # full RGB spectrum noise
    leds.simplex(SimplexMode.FULLRGB)
elif mode == 'purple':
    leds.simplex(SimplexMode.COLOR1, [(255, 0, 255)])
elif mode in schemes: # use a second noise source for the tint
    leds.simplex(SimplexMode.COLOR2, schemes[mode])
else:
    print(f'Unknown mode {mode}')

